import Head from "next/head";
import type { NextPage } from "next";
import DragToCanvasPage from "@pages/DragToCanvasPage";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DragToCanvasPage />
    </>
  );
};

export default Home;
