import Head from 'next/head';
import type {NextPage} from 'next'
import ThreeDraggable from "@model/ThreeDraggable/Container";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <ThreeDraggable/>
        </>
    )
}

export default Home
